baseURL = "https://ralphbrooks.github.io/"
languageCode = "en-us"
title = "Ralph Brooks"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-140484526-1"