baseURL = "https://ralphbrooks.com/"
languageCode = "en-us"
title = "Ralph Brooks"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]