baseurl = "https://ralphabrooks.com/"
languageCode = "en-us"
title = "AI Best Practices"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-140484526-1"

enableRobotsTXT=true